from schemas.finance import (
    FactureSchema,
    FactureDetailedSchema,
    FactureCreateSchema,
    FactureUpdateSchema,
    DetailsFactureSchema,
    DetailsFactureDetailedSchema,
    DetailsFactureCreateSchema,
    DetailsFactureUpdateSchema,
)

from schemas.medical import (
    OrdonnanceSchema,
    OrdonnanceDetailedSchema,
    OrdonnanceCreateSchema,
    OrdonnanceUpdateSchema,
    FicheConsultationSchema,
    FicheConsultationDetailedSchema,
    FicheConsultationCreateSchema,
    FicheConsultationUpdateSchema,
    PrescriptionSchema,
    PrescriptionDetailedSchema,
    PrescriptionCreateSchema,
    PrescriptionUpdateSchema,
    AntecedentSchema,
    AntecedentDetailedSchema,
    AntecedentCreateSchema,
    AntecedentUpdateSchema,
    SigneVitalSchema,
    SigneVitalDetailedSchema,
    SigneVitalCreateSchema,
    SigneVitalUpdateSchema,
    ExamenPhysiqueSchema,
    ExamenPhysiqueDetailedSchema,
    ExamenPhysiqueCreateSchema,
    ExamenPhysiqueUpdateSchema,
    ServiceMedicalSchema,
    ServiceMedicalDetailedSchema,
    ServiceMedicalCreateSchema,
    ServiceMedicalUpdateSchema,
    ImageMedicalSchema,
    ImageMedicalDetailedSchema,
    ImageMedicalCreateSchema,
    ImageMedicalUpdateSchema,
    ParacliniqueEssentielleSchema,
    ParacliniqueEssentielleDetailedSchema,
    ParacliniqueEssentielleCreateSchema,
    ParacliniqueEssentielleUpdateSchema,
)

from schemas.operation import (
    ReceptionSchema,
    ReceptionDetailedSchema,
    ReceptionCreateSchema,
    ReceptionUpdateSchema,
    ActeChirurgicalSchema,
    ActeChirurgicalDetailedSchema,
    ActeChirurgicalCreateSchema,
    ActeChirurgicalUpdateSchema,
)

from schemas.patient import (
    PatientSchema,
    PatientDetailedSchema,
    PatientCreateSchema,
    PatientUpdateSchema,
    HospitalisationSchema,
    HospitalisationDetailedSchema,
    HospitalisationCreateSchema,
    HospitalisationUpdateSchema,
    ChambreSchema,
    ChambreDetailedSchema,
    ChambreCreateSchema,
    ChambreUpdateSchema,
)

from schemas.pharmacie import (
    MedicamentSchema,
    MedicamentDetailedSchema,
    MedicamentCreateSchema,
    MedicamentUpdateSchema,
    StockSchema,
    StockDetailedSchema,
    StockCreateSchema,
    StockUpdateSchema,
)

from schemas.utilisateur import (
    EmployeSchema,
    EmployeDetailedSchema,
    EmployeCreateSchema,
    EmployeUpdateSchema,
    MedecinSchema,
    MedecinDetailedSchema,
    MedecinCreateSchema,
    MedecinUpdateSchema,
    ReceptionnisteSchema,
    ReceptionnisteDetailedSchema,
    ReceptionnisteCreateSchema,
    ReceptionnisteUpdateSchema,
    PharmacienSchema,
    PharmacienDetailedSchema,
    PharmacienCreateSchema,
    PharmacienUpdateSchema,
    InfirmierSchema,
    InfirmierDetailedSchema,
    InfirmierCreateSchema,
    InfirmierUpdateSchema,
    CaissierSchema,
    CaissierDetailedSchema,
    CaissierCreateSchema,
    CaissierUpdateSchema,
    CompteSchema,
    CompteDetailedSchema,
    CompteCreateSchema,
    CompteUpdateSchema,
)


from schemas.association import (
    AssociationChambreInfirmierSchema,
    AssociationChambreInfirmierDetailedSchema,
    AssociationChambreInfirmierCreateSchema,
    AssociationChambreInfirmierUpdateSchema,
    AssociationActeChirurgicalEmployeSchema,
    AssociationActeChirurgicalEmployeDetailedSchema,
    AssociationActeChirurgicalEmployeCreateSchema,
    AssociationActeChirurgicalEmployeUpdateSchema,
    AssociationMedicamentPrescriptionSchema,
    AssociationMedicamentPrescriptionDetailedSchema,
    AssociationMedicamentPrescriptionCreateSchema,
    AssociationMedicamentPrescriptionUpdateSchema
)
